modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="geriorandomstuff"
version="1.0.0"
displayName="Randomness"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/TRRESTGHGYTCFTGBCXSZD"
authors="GerioSB"

[[dependencies.geriorandomstuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.geriorandomstuff]]
    modId="mekanism"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.geriorandomstuff]]
    modId="appeng"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.geriorandomstuff]]
    modId="com.simibubi.create"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

