modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="technicalsprunki"
version="1.0.0"
displayName="Gerio's Sprunki"
credits="私のパンチを受けてみろ"
displayURL="https://github.com/TRRESTGHGYTCFTGBCXSZD"
authors="GerioSB"

[[dependencies.geriorandomstuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

